name: Build and Release

permissions:
    contents: write

on:
    push:
        branches:
            - master
    workflow_dispatch:

jobs:
    build-and-release:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout source
              uses: actions/checkout@v4

            - name: Set up Node.js
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Install pnpm
              run: npm install -g pnpm

            - name: Install dependencies
              run: pnpm install --frozen-lockfile

            - name: Get package version
              id: version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./package.json').version")
                  SHORT_SHA=$(git rev-parse --short HEAD)
                  echo "version=$PACKAGE_VERSION" >> $GITHUB_OUTPUT
                  echo "short_sha=$SHORT_SHA" >> $GITHUB_OUTPUT

            - name: Build userscript
              run: pnpm build userscript ${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}

            - name: Build bundle
              run: pnpm build bundle ${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}

            - name: Check if version already exists on npm
              id: check_version
              run: |
                  PACKAGE_VERSION=$(node -p "require('./plugins/package.json').version")
                  echo "Checking version $PACKAGE_VERSION..."
                  REGISTRY_VERSION=$(npm view @readit-mod/plugins version || echo "0.0.0")
                  if [ "$PACKAGE_VERSION" = "$REGISTRY_VERSION" ]; then
                      echo "Version $PACKAGE_VERSION already exists. Skipping publish."
                      echo "skip=true" >> $GITHUB_OUTPUT
                  else
                      echo "Version $PACKAGE_VERSION is new. Proceeding with publish."
                      echo "skip=false" >> $GITHUB_OUTPUT
                  fi
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Publish plugin package to npm
              if: steps.check_version.outputs.skip == 'false'
              run: |
                  cd plugins
                  pnpm publish --no-git-checks --access public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

            - name: Check if release already exists
              id: check_release
              run: |
                  if gh release view "v${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}" >/dev/null 2>&1; then
                    echo "exists=true" >> $GITHUB_OUTPUT
                  else
                    echo "exists=false" >> $GITHUB_OUTPUT
                  fi
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

            - name: Create GitHub release
              if: steps.check_release.outputs.exists == 'false'
              uses: softprops/action-gh-release@v2
              with:
                  tag_name: v${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}
                  name: ${{ steps.version.outputs.version }}-${{ steps.version.outputs.short_sha }}
                  body: |
                      Automated release for version ${{ steps.version.outputs.version }} (commit ${{ steps.version.outputs.short_sha }}).
                  files: |
                      dist/readit.user.js
                      dist/readit.bundle.js
                      dist/manifest.json
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
